### ISSUE TITLE
miss split.mat.My GTA5 datasets don't have split.map.where can obtain it

### ISSUE THREAD

**Issue by yuheyuan** [dvlab-research/DecoupleNet#2]
I'm interested in this work.
expecting second training code.

**Comment by yuheyuan** [comment]
```txt
FileNotFoundError: [Errno 2] No such file or directory: '/media/ailab/data/yy/data/gta/split.mat'

```

**Comment by X-Lai** [comment]
Thank you very much for your interest. We will release the second-phase training script soon. For the split.mat, it should be within the official GTA5 dataset.

**Comment by yuheyuan** [comment]
> Thank you very much for your interest. We will release the second-phase training script soon. For the split.mat, it should be within the official GTA5 dataset.


yes, I find the split.mat. Anthoer question, how long the train. I run the code to train on one 3090 GPU. I want to know the time of the train because I find the train time may be long. Some code they don't finish the all train. I want to know if this need finish all iteration.

**Comment by X-Lai** [comment]
Yes, finishing all iterations can reproduce our result. Using 4 GPUs for training is recommended.

**Comment by X-Lai** [comment]
Hi, the second-phase training script is released now. Welcome to open issues if having questions.
