### ISSUE TITLE
GPU memory consumption

### ISSUE THREAD

**Issue by m1rakram** [dvlab-research/DecoupleNet#3]
Hi, thank for the paper and amazingly clear code. I am trying to implement it for my project. However, I noticed one problem that should be considered. While you were recording the losses by using += symbols and without .item() (which takes only value) you were storing all states in whole epoch. I don't now if it is problem in distributed GPU, but in single GPU that i am using, after some iterations it is out of memory of GPU because of storing every state of loss. When I used .item() gpu usage became stable. It would be better if you consider it in your code.

I tried to express my concern and possible problems in your code. Good luck!
Thanks

**Comment by X-Lai** [comment]
Thank you for your interest in our work.

As for your concern, in [here](https://github.com/dvlab-research/DecoupleNet/blob/main/train_phase1.py#L578), we actually have used .item() to take the tensor value only. So I think it should be no memory issue here.

Welcome to point out any further issue.

**Comment by m1rakram** [comment]
Thanks for your answer, 
if you can check the same script at line 550 and 569. They are storing states also

**Comment by X-Lai** [comment]
Yes, but before starting the next step, the memory will be freed automatically.

**Comment by m1rakram** [comment]
Fair, Thanks a lot
